---
title: "How has COVID-19 impacted public transit?"
date: "June 22, 2020"
output: html_document
slug: covid-built-environment-transit
categories: []
tags:
  - COVID-19
  - Transit
subtitle: ''
summary: "The consequences of COVID-19 for public transit"
authors:
  - robin-basalaev-binder
  - akili-atherley
lastmod: '2020-06-22T17:00:06-04:00'
featured: yes
image:
  placement: 1
  focal point: smart
  caption: Photo by [John Brighenti](https://www.flickr.com/photos/alchemist_x/49210599167/)
projects:
  - spatial-analysis-of-covid-19
---

*This is a continuation of our series, __COVID-19 and the urban environment__.*

From the first emergence of the COVID-19 pandemic in Wuhan, China to its worldwide spread, the disease has commonly been understood as an urban phenomenon. Urban areas have been hit the hardest, and even those with lesser outbreaks have already seen significant changes to work and social life, and to their urban landscapes and built forms. Over the next several weeks, we will be releasing findings from research we conducted this past summer on COVID and urban life. We aim to provide a broad look at current responses, tactics, and consequences of the pandemic.

**Public transit**

Public transit is a major form of transportation in many countries around the world,  consisting of buses, light rail, subways, streetcars, and even water taxis, according to the American Public Transportation Association (2020). In Canada, the percentage of people who commute to work by public transit increased from 10.1% in 1996 to 12.4% in 2016 (Statistics Canada, 2017). In the U.S., 9.9 billion trips were taken on public transportation in 2018 (American Public Transportation Association, 2020) while in the United Kingdom (U.K.), there were 8.3 billion passenger journeys on public transport vehicles between 2018 and 2019 according to the Department for Transport (2019). 

With preliminary evidence that SARS-CoV-2 is partially transmitted through contact with surfaces (Dietz et al, 2020), it is therefore critical to try to understand the relationship between the transmission of the virus and different aspects of the built environment, including human behaviour, spatial dynamics and building operational factors that can encourage or mitigate the spread of  COVID-19 (Dietz et al, 2020) within the context of public transit.

The COVID-19 pandemic has had a significant impact on public transportation systems. In Wuhan, the epicenter of the outbreak in China (Schultz, 2020), public transport was temporarily brought to a halt amid efforts to contain the spread of the virus (Xu, 2020). In late March, amid concerns about virus transmission, demand for public transport in Canada dropped by an average of 83 percent compared to previous years, and similar patterns were seen in France (CBC News, 2020) and the U.S. (Hawkins, 2020).

The Canadian Urban Transit Association (CUTA, 2020) identified public transport as a high-risk environment for the transmission of COVID-19 due to the high number of people in a confined space with limited ventilation, no access control to identify potentially sick persons, and a variety of frequently-touched surfaces. Dietz et al. (2020) also note that the increase in exposure can also be attributed to the change in modes of transportation from single occupancy vehicles to rideshare programs or transportation network companies. 

Despite the fact that transmission of COVID-19 has only been documented via respiratory droplet spread rather than through deposition on fomites, steps should still be taken to clean and disinfect all potential sources of COVID-19 under the assumption that active viruses may be transmitted by contact with these abiotic surfaces (Dietz et al, 2020). Some public transportation networks have committed to cleaning and disinfecting buses, subways and other modes of public transportation. According to Li & Chapman (2020), The New York City subway system, for the first time in over a century of operation, sent crews of cleaners and police officers to disinfect trains. In an effort to mitigate the COVID-19 epidemic, the city’s 472 stations will be closing everyday between 1 a.m. and 5 a.m for its thousands of subway cars to be cleaned (Li & Chapman, 2020). TransLink, the regional transportation network in Metro Vancouver, also stepped up the cleaning of their vehicles to prevent the spread of COVID-19 (Little, 2020). This is based on the premise that since coronaviruses are enveloped viruses, by which the envelope which protects them is made of lipids or grease, can be easily dissolved by cleaners which leaves the virus itself vulnerable (Chung, 2020). This renders them as an easy virus to kill with the appropriate disinfectant used (Chung, 2020).

According to Boone & Gerba (2007), in a study done by Krilov et al. (1996) of a day care centre, it was found that when environmental surfaces such as buses and toys were regularly cleaned, there was a reduction in gastrointestinal and respiratory illnesses among children. Another study conducted in 1980 by Carter et al.found that families using an iodine-based hand wash had lower rates of respiratory disease (Boone & Gerba, 2007). Additionally, a review article by Barker et al. cited over 15 research studies that found that a decrease in viral contamination and viral infection occurred when hand washing was used regularly as an intervention (Boone & Gerba, 2007). From these studies, it can thus be said that with adequate hygiene intervention and regular disinfection, the likelihood of a disease transmission, such as COVID-19, can be reduced significantly. 
Not everyone believes public transit is a vector of transmission of COVID-19, however. According to Miller (2020), there is no evidence in Canada that travelling on public transit increases the chances of contracting novel coronavirus. Dr. Alon Vaisman noted that while the measures taken to clean and disinfect surfaces is commendable, the likelihood of someone contracting the virus on public transportation is low (Miller, 2020).

---

<font size = 3>**REFERENCES**

American Public Transportation Association. (2020, February 10). Public Transportation Facts. 
Retrieved from https://www.apta.com/news-publications/public-transportation-facts/

Boone, S. A., & Gerba, C. P. (2007). Significance of Fomites in the Spread of Respiratory and Enteric Viral Disease. Applied and Environmental Microbiology, 73(6), 1687–1696. doi: 10.1128/aem.02051-06

CBC News. (2020, March 27). How COVID-19 is affecting public transit use | CBC News. Retrieved from https://www.cbc.ca/news/canada/coronavirus-covid19-public-transit-1.5509927

Canadian Urban Transit Association. (2020, May 11). Coronavirus disease (COVID-19): Outbreak updates - Public Health Agency of Canada. Retrieved from https://cutaactu.ca/en/covid-19

Dietz, L., Horve, P. F., Coil, D., Fretz, M., Eisen, J., & Wymelenberg, K. V. D. (2020). 2019 Novel Coronavirus (COVID-19) Pandemic: Built Environment Considerations To Reduce Transmission. doi: 10.20944/preprints202003.0197.v3

Hawkins, A. J. (2020, March 13). Coronavirus is taking a big bite out of public transportation ridership in the US. Retrieved from https://www.theverge.com/2020/3/13/21179032/public-transportation-coronavirus-covid19-ridership-nyc-sf-la-dc

Krilov, L. R., Barone, S. R., Mandel, F. S., Cusack, T. M., Gaber, D. J., & Rubino, J. R. (1996). Impact of an infection control program in a specialized preschool. American Journal of Infection Control, 24(3), 167–173. doi: 10.1016/s0196-6553(96)90008-5

Li, S., & Chapman, B. (2020, May 6). New York City Subway Begins Nightly Shutdowns for Coronavirus Cleaning. Retrieved from https://www.wsj.com/articles/new-york-city-subway-begins-nightly-shutdowns-for-coronavirus-cleaning-11588767945

Little, S. (2020, March 7). How TransLink is stepping up cleaning to prevent COVID-19 transmission. Retrieved from https://globalnews.ca/news/6643771/translink-covid-sanitization/

Miller, J. (2020, March 5). Does your risk of coronavirus exposure increase on public transit? We had a Toronto doctor explain the risk. Retrieved from https://www.thestar.com/news/gta/2020/03/04/do-your-chances-of-getting-the-coronavirus-increase-on-public-transit-we-had-a-toronto-doctor-explain-the-risk.html

Statistics Canada. (2017, November 29). Journey to work: Key results from the 2016 Census. Retrieved from https://www150.statcan.gc.ca/n1/daily-quotidien/171129/dq171129c-eng.htm

Schultz, J. (2020, March 18). Inside Wuhan, epicenter of China's coronavirus outbreak | Pictures. Retrieved from https://www.reuters.com/news/picture/inside-wuhan-epicenter-of-chinas-coronav-idUSRTS2ZL3I

Xu, Y. (2020, January 22). Public Transport In Wuhan Suspended Due To Coronavirus Concerns. Retrieved from https://www.npr.org/sections/goatsandsoda/2020/01/22/798602296/public-transport-in-wuhan-suspended-due-to-coronavirus-concerns
