---
title: "Does dense urban living spread COVID?"
date: "November 30, 2020"
output: html_document
slug: covid-built-environment-density
categories: []
tags:
  - Housing
  - COVID
subtitle: ''
summary: "The consequences of COVID for compact development"
authors:
  - robin-basalaev-binder
  - akili-atherley
lastmod: '2020-11-30T17:00:06-04:00'
featured: yes
image:
  placement: 1
  focal point: smart
  caption: Photo by [Alan Stanton](https://www.flickr.com/photos/alanstanton/15080619725/in/photolist-oYC7QV-21inHSo-bCWhDp-DvQPtj-21cVaTX-22Ry7up-Y4k9qN-22TDqXt-JgvRJ4-Zs9isH-225FvMS-WfcVG3-Z68X62-YxHbmj-2hmJ6Mn-e1H3VT-2ehhMp5-29U79uz-9SfiNf-fDe1BY-CFcD6b-6GJDYA-yB2kGt-oknLZe-a7mwpG-9D49yi-a91KFY-61zbh2-cEdKfG-XfPnNL-6XxNsU-8D6ZKr-pZM1kP-61zaut-6GJvxu-d8Gw3m-a8XWGV-8Daa4J-a8XW7i-a8XU1e-cEdHoN-6GJArJ-a8XUTk-6GKUJY-a8XXNa-a8XUor-a8XUWx-a91JUA-a91NwY-8sssv4)
projects:
  - COVID
---

*This is the first part of our series, __COVID-19 and the urban environment__.*

From the first emergence of the COVID-19 pandemic in Wuhan, China to its worldwide spread, the disease has commonly been understood as an urban phenomenon. Urban areas have been hit the hardest, and even those with lesser outbreaks have already seen significant changes to work and social life, and to their urban landscapes and built forms. Over the next several weeks, we will be releasing findings from research we conducted this past summer on COVID and urban life. We aim to provide a broad look at current responses, tactics, and consequences of the pandemic.

**The built environment**

The built environment refers to the totality of human-constructed spaces in which most people live most of their lives, including buildings, transportation systems, and public space (Dietz et al, 2020). The design of the built environment can promote health by advancing active transportation, providing access to clean air and shade, and fostering opportunities for social interaction and cohesion (Oppel, 2020). Despite some earlier evidence that viruses may be recovered through fomites (porous and non-porous surfaces) (Boone & Gerba, 2007), surfaces are not necessarily a significant cause of transmission as we now know that COVID-19 is primarily spread through aerosols. This implies that physical distancing, good ventilation and good hygiene practices are the centerpiece of preventative measures (Oppel, 2020), and raises questions about the role of indoor areas and public spaces in dense urban environments during COVID. Over the next few weeks, we will unpack our findings on the impact of COVID-19 on various elements of the built environment, starting with density. 

**A disease of density?**

The outbreak of COVID-19 in major cities across the world is challenging the way people perceive urban growth. “This is not life as usual. There is a density level in NYC that is destructive. It has to stop, and it has to stop now. NYC must develop an immediate plan to reduce density,” tweeted Governor Andrew Cuomo (2020) on March 22 while presiding over one of the deadliest concentrations of the outbreak.

While Cuomo's perspective was common in the early days of the pandemic, even in Spring 2020 there were signs pointing in the other direction. For one, many hyper-dense Asian cities such as Seoul, Singapore, Hong Kong, and Tokyo managed to contain the virus with early detection and strict quarantine enforcement (Patino, 2020).

A later analysis by New York University’s Furman Center (2020) found that, while “COVID-19 is more prevalent in areas where more people reside in crowded units,” the “[o]verall population density is not associated with higher rates of COVID-19 cases.” Even when density is examined in its various aspects — number of inhabitants per area, number of units in a building, and number of residents per unit — the result remains the same: there is no significant correlation between density (or even overcrowding) and higher rates of COVID-19 (Fox, 2020). 

A study from the London School of Economics and Political Science looking at the link between COVID-19 spread and density further found that while urban density seems to have affected the timing of COVID-19 outbreaks, it found “no evidence that population density is linked with COVID-10 incidence once [it adjusts] for the timing of the onset of the disease…” (Carozzi et al., 2020). Hamidi et al. (2020) note that urban areas with more counties that have economic, social, and commuting links to each other are more vulnerable to COVID-19 outbreaks, suggesting that connectivity matters more than density, also applicable to places in China with more connectivity to Wuhan (Lin et al., 2020). They further found a negative correlation between county density and COVID-19 mortality rates (ibid). Areas with high density are additionally often better prepared and have better access to resources than lower-density areas when faced with public health emergencies such as COVID-19. 

As the pandemic nears its 12th month and populations across the globe continue to struggle to adjust to their new realities, many perspectives on cities and city life have emerged. Many dozens of media articles have been published declaring a mass exodus from cities to the suburbs amidst the pandemic, often referencing density and related factors as the reason and contributing, directly and indirectly, to the conversation on density and cities (e.g. Bahney, 2020; Marsh, 2020; Mull 2020). The numbers do not paint a clear picture, yet the conversation continues. According to Zillow’s 2020 urban-suburban market report, suburban housing markets in the United States have not disproportionately increased compared to urban ones, and both are presently “hot sellers” (Zillow, 2020). In Canada, some cities have seen increased prices for single family homes in the suburbs, such as Montreal’s North Shore where median prices increased 27% since 2019 (Balakrishnan, 2020a). In Toronto, condo sales in the suburbs rose 28.4% since 2019, and fell 8.5% in the City of Toronto (Balakrishnan, 2020b). Despite any ambiguity in the rates of people leaving or entering urban areas, radical changes can already be seen in urban environments, and the necessity for urban areas to communicate, to act as a network and in solidarity remains (Acuto et al., 2020).

Despite the many advantages to urban living such as lower rates of obesity and lower infrastructural costs, the truth is, cities are meant to bring people together both intellectually and physically, which makes social distancing nearly impossible when a city works well. Furthermore, research shows that “density preferences may be more stable than many of the other perceptions studied so far and, correspondingly, efforts to change densities will likely have to be accompanied by extensive efforts to win over skeptical publics” (Hooper, 2020). 

----

<font size = 3>**REFERENCES**

Acuto, M., Larcom, S., Keil, R., Ghojeh, M., Lindsay, T., Camponeschi, C., & Parnell, S. (2020). Seeing COVID-19 through an urban lens. Nature Sustainability, 1-2.

Bahney, A. (2020, September 1). These people have left big cities for good. Here's where they landed. CNN. Retrieved from https://www.cnn.com/2020/08/31/success/leaving-the-city-for-suburbs/index.html 

Balakrishnan, A. (2020a, October 12). As suburban homes get big-city price tags, longer commutes look like better deals. The Globe and Mail. https://www.theglobeandmail.com/real-estate/article-as-suburban-homes-get-big-city-price-tags-longer-commutes-look-like/ 

Balakrishnan, A. (2020b, November 4). Toronto home prices rise 13.7 per cent year-over-year. The Canadian Press. https://www.cp24.com/news/toronto-home-prices-rise-13-7-per-cent-year-over-year-1.5174770 

Boone, S. A., & Gerba, C. P. (2007). Significance of Fomites in the Spread of Respiratory and Enteric Viral Disease. Applied and Environmental Microbiology, 73(6), 1687–1696. doi: 10.1128/aem.02051-06

Carozzi, F., Provenzano, S., Roth, S. (2020). Urban Density and COVID-19. Discussion paper series. Retrieved from https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3643204 

Cuomo, A. [@NYGovCuomo]. (2020, March 22). This is not life as usual. There is a density level in NYC that is destructive. It has to stop [Tweet]. Twitter. https://twitter.com/nygovcuomo/status/1241750717939007490?lang=en

Dietz, L., Horve, P. F., Coil, D., Fretz, M., Eisen, J., & Wymelenberg, K. V. D. (2020). 2019 Novel Coronavirus (COVID-19) Pandemic: Built Environment Considerations To Reduce Transmission. doi: 10.20944/preprints202003.0197.v3

Fox, J. (2020, April 7). Density isn’t destiny in the fight against Covid-19. Bloomberg. https://www.bloomberg.com/opinion/articles/2020-04-07/new-york-san-francisco-show-why-density-isn-t-doom-in-pandemic?sref=C3P1bRLC

Hamidi, S., Sabouri, S., & Ewing, R. (2020). Does density aggravate the COVID-19 pandemic? Early findings and lessons for planners. Journal of the American Planning Association, 86(4), 495-509.

Hooper, M. (2020, April 13). Pandemics and the future of urban density: Michael Hooper on hygiene, public perception and the “urban penalty”. Harvard University Graduate School of Design. https://www.gsd.harvard.edu/2020/04/have-we-embraced-urban-density-to-our-own-peril-michael-hooper-on-hygiene-public-perception-and-the-urban-penalty-in-a-global-pandemic/

Kolko, J. (2020, April 15). Where COVID19 death rates are highest. Jed Kolko. http://jedkolko.com/2020/04/15/where-covid19-death-rates-are-highest/

Lin, C., Lau, A. K., Fung, J. C., Guo, C., Chan, J. W., Yeung, D. W., ... & Lao, X. Q. (2020). A mechanism-based parameterisation scheme to investigate the association between transmission rate of COVID-19 and meteorological factors on plains in China. Science of the Total Environment, 737, 140348.

Marsh, S. (2020, September 26). Escape to the country: how Covid is driving an exodus from Britain’s cities. The Guardian. Retrieved from https://www.theguardian.com/world/2020/sep/26/escape-country-covid-exodus-britain-cities-pandemic-urban-green-space 

Mull, A. (2020, June 15). The High Cost of Panic-Moving. The Atlantic. Retrieved from https://www.theatlantic.com/health/archive/2020/06/pandemic-cities-moving-remote-work/613069/ 

NYU Furman Center. (2020, April 10). COVID-19 cases in New York City, a neighborhood-level analysis. NYU Furman Center. https://furmancenter.org/thestoop/entry/covid-19-cases-in-new-york-city-a-neighborhood-level-analysis

Oppel, L. (2020). Concrete versus COVID-19: How the built environment can limit the spread of disease. BC Medical Journal, 62(4), 134.

Patino, M. (2020, March 31). Why Asian countries have succeeded in flattening the curve. CityLab. https://www.citylab.com/life/2020/03/coronavirus-stay-at-home-order-lockdown-social-distancing/608857/

Zillow. (2020, August 12). Zillow 2020 Urban-Suburban Market Report. Retrieved from https://www.zillow.com/research/2020-urb-suburb-market-report-27712/</font>
