---
title: "UPGO Alumnus Lou Seltz Featured in Speculative Life Cluster"
author: "Charlotte Belot"
date: '2020-06-12'
output: html_document
slug: UPGO-alumnus-featured-speculative-life
categories: []
tags:
  - Housing
  - Landlords
  - Debt
subtitle: ''
summary: "Two pieces on the COVID-19 pandemic, housing precarity, and the rental market in Canada"
authors:
  - charlotte-belot
lastmod: '2020-06-12T17:00:06-04:00'
featured: yes
image:
  placement: 1
  focal point: smart
  caption: Photo by Charlotte Belot
projects:
  - Short-term rentals

---

UPGo alumnus Lou Seltz (McGill MUP 2020) recently published two pieces on the COVID-19 pandemic, housing precarity, and the rental housing market on the Speculative Life Cluster blog.

The [first article](https://speculativelife.com/debt-precarity-and-the-pandemic/2020/6/9/qfeoa70hx9qxaicc79aeww6agpia6l), published earlier this month, looks at the potential benefits of the pandemic for Montreal's long-term rental market, which prior to the pandemic was experiencing very low vacancy rates. In the wake of vastly reduced travel, many units that had been converted to full-time Airbnb listings found their way back onto the long-term rental market. 

In the [second piece](https://speculativelife.com/debt-precarity-and-the-pandemic/2020/6/12/a-rent-strike-was-inevitable) from today discusses the inevitability of a rent strike, given the relative lack of government support to renters after pandemic-related business closures and the imposition of stay-at-home orders.  

Lou was a research assistant at UPGo from mid-2019 until her graduation from McGill's Master of Urban Planning program in spring 2020, and completed her supervised research project on big data, short-term rentals, and professional host behaviour.

