---
title: "Toronto's STR bylaws are good planning: UPGo position paper"
date: '2019-11-20'
type: "post"
slug: toronto-str-bylaws-report
categories: []
tags:
  - Publication
  - Short-term rentals
  - Toronto
subtitle: ''
summary: "An empirical and research-based analysis of the newly approved STR bylaws in Toronto"
authors:
  - admin
lastmod: '2019-11-20T07:00:06-04:00'
featured: yes
image:
  placement: 2
  caption: 'Credit: dconvertini'
projects:
  - short-term-rentals
---

Short-term rentals (STRs) are not currently permitted in the City of Toronto. In December 2017 and January 2018, City Council introduced new regulations on STRs in Toronto, including amendments to the zoning bylaws, which would limit STRs to a host's principal residence. These amendments were appealed to the provincial Local Planning Appeal Tribunal (LPAT), which held a hearing in August and September 2019. This week the LPAT released [its ruling](https://fairbnb.ca/wp-content/uploads/2019/11/PL180082-NOV-18-2019.pdf), which dismissed the appeal in its entirety, and allows the bylaws to come into effect. (See the Globe and Mail's coverage [here](https://www.theglobeandmail.com/canada/toronto/article-toronto-limits-on-airbnb-and-other-short-term-rentals-will-go-ahead/).)

I was honoured to serve as an expert witness in the hearings, providing evidence both on the current state of the STR market in Toronto and on the likely impacts of the regulations were they to come into force. In preparation for my testimony, the whole UPGo team spent some time compiling a series of policy positions on the proposed bylaws, informed by our own ongoing research and by the research of other scholars.

Our intention was to release this material prior to the hearings, but we ultimately decided to release only the empirical snapshot of the Toronto STR market ([Short-term rentals in Toronto: UPGo city spotlight](/publication/short-term-rentals-in-toronto)), and to communicate our opinions about the appropriateness and impacts of the proposed bylaw amendments through my direct testimony in the hearings.

Now that the tribunal has released its decision, I am very happy to be able to release our own analysis of the bylaws. I am encouraged to see that our main points were reflected quite closely in the tribunal's decision. The full report, titled [Toronto's STR bylaws are good planning: UPGo position paper](/publication/toronto-str-bylaws), is available now for download. Below I summarize our main conclusions from the work.


### The bottom line

The STR bylaws approved by Toronto City Council in 2017 and 2018 constitute good planning, both in terms of adequately representing the public’s interest and adhering to the objectives and policies set out in Toronto’s Official Plan. The vision of the Plan is a Toronto with vibrant and complete communities, affordable housing choices, attractive and walkable neighbourhoods, a healthy natural environment, and a strong and competitive economy with well-paid, stable, safe, and fulfilling employment opportunities. The STR bylaws support this vision by protecting the city’s long-term housing stock, preventing the displacement of existing residents, and strengthening urban planning capacity. By regulating commercial operations of short-term rentals, particularly by restricting short-term rentals to a host’s principal residence, Toronto will be better able to keep housing affordable and available for Toronto residents.


### Toronto's short-term rental market

- On April 30, 2019, there were 21,000 short-term rentals active in the City of Toronto—a 10.9% year-over-year increase.

- Toronto has the most STR listings of any city in the country, and generates by far the most revenue. The city's 14,000 STR hosts earned $208 million in revenue last year.

- STR listings in Toronto are heavily concentrated in the downtown area, with a secondary concentration near Yonge and Sheppard.

- Toronto’s STR market is dominated by entire- home listings, which represent two thirds of active listings and five sixths of host revenue. The majority of entire- home STR listings in Toronto are studio (9.7%) or one-bedroom (51.7%) units. 12.6% of entire-home listings are hosted in housing units with three or more bedrooms, which is considered family-appropriate housing by the City.

- STR revenue in Toronto is distributed in a highly unequal fashion: more than two fifths of all revenue last year was earned by just one in twenty hosts, and the most successful ten percent of hosts earned fully 56.4% of all STR revenue.

- Nearly two fifths (37.9%) of active listings were commercial multilistings (listings controlled by a host with two or more entire-home listings or three or more private- room listings), which earned 53.3% of total host revenue.

- STRs have removed more than 5,500 housing units from Toronto’s long-term housing market. 4,800 of these were frequently rented entire-home listings, and 745 were clusters of private-room listings operating out of the same housing unit. The equivalent figure one year ago was less than 4,500, which means that there has been a 24.3% increase in STR-induced housing loss in the City of Toronto in the last twelve months—a much higher growth rate than the growth in total active listings (10.9%).

- There are approximately the same number of housing units converted to dedicated short-term rentals in
Toronto as there are housing units vacant and available for rent. This means that, if commercial STRs were converted back to long-term housing, this would be equivalent to doubling the rental vacancy rate in the short-term, and bringing down rents in the long-term.

- Approximately 40% of Toronto STR listings are likely in violation of the STR bylaws’ prinicipal residence requirement. These 8,700 listings would not be permitted if the bylaws come into effect.


### Short-term rentals and housing loss in Toronto

The conversion of long-term housing into commercial short-term rental operations has direct and substantial impacts on housing availability and affordability for residents. By contrast, true “home-sharing”, where a resident activates extra capacity in their dwelling by renting it temporarily to a visitor, has fewer negative effects on housing affordability and availability. The proposed bylaws would allow for “home-sharing”, while restricting commercial operations that have been removing more than 5,500 units of housing from the long- term market in Toronto.


### The impact of short-term rentals on Toronto neighbourhoods

STRs have been shown to incentivize displacement of long-term residents, particularly from walkable neighbourhoods. This can substantially change the form and functioning of residential areas. STRs may bring new sources of revenues into neighbourhoods, but the majority of this benefit is accrued by STR hosts themselves, many of whom are not actually local residents. While this select group benefits, neighbours must bear the brunt of negative externalities from living next to tourist residences, including increased noise and nuisance. In addition, an abundance of STRs in communities has been shown to negatively disrupt neighbourhoods through increased health and safety issues, and social impacts such as reduced community character and cohesion. By limiting STRs to principal residences, Toronto’s bylaws would reduce negative externalities associated with commercial STRs while continuing to allow home-sharing to flourish.


### The economic impact of short-term rentals

The influx of tourism dollars into a neighbourhood from STRs comes at the expense of housing availability and displaces long-term residents in favour of tourists. This leads to neighbourhood economies that prioritize catering to the desires of tourists rather than to the day-to-day needs of locals. Furthermore, studies have shown that STR operations disproportionately benefit white operators and neighbourhoods, raising questions of social and racial equity. Research has also demonstrated the negative impacts of STRs on the traditional hotel industry, with lower-end and independent hotels most seriously affected. Finally, we argue that although commercial-scale STR operations create new employment opportunities in supporting industries such as property
management and maintenance, these jobs are often casual, short-term, and exploitative because they lack the union-eligibility and other employee protections available to equivalent hotel-industry workers. The jobs created by commercial STR companies do not diversify the economic base, as the fundamental concept of the industry parallels that of the traditional hotel.


### Recommendation: The short-term rental bylaws should be upheld

The STR bylaws approved by City Council in 2017 and 2018 represent good planning and should be fully upheld by the Local Planning Appeal Tribunal. By supporting housing security, protecting existing rental stock, and regulating the use of new construction in a housing market with an extremely low — 1.1% — rental vacancy rate, the STR bylaws support the goals of housing availability and
affordability. Additionally, the bylaws protect the character of Toronto’s unique residential neighbourhoods, supporting community cohesion and social capital. The proposed regulations reduce the precariousness of an unsustainable economic market, and ultimately, strengthen urban planning efforts towards a future consistent with the City of Toronto’s Official Plan.

---

'Toronto's STR bylaws are good planning: UPGo position paper' is [publicly available for download today](/publication/toronto-str-bylaws).