---
title: "How has COVID affected social inequities?"
date: "January 4, 2020"
output: html_document
slug: covid-built-environment-social-inequities
categories: []
tags:
  - COVID-19
subtitle: ''
summary: "A summary of the impacts of COVID-19 on urban social justice"
authors:
  - robin-basalaev-binder
  - jenni-chung
lastmod: '2021-01-04T17:00:06-04:00'
featured: yes
image:
  placement: 1
  focal point: smart
  caption: Photo by [Michael Swan](https://www.flickr.com/photos/mmmswan/49778097898/in/photolist-2iQLucw-2iQHLgd-2iQHLje-2jEDpiq-2jayP6A-2iQLuf7-2j6e2VC-2iQLuqx-2j6e3xj-2iQHLo2-2iQLuja-2iQNbV9-2iTJNte-2kaJkqx-2iQNbBD-2j3ruLi-2iQHKXN-2jpBQAz-2iGHuGL-2jiWsVb-2j3t26q-2jmaf7K-2jtnfuS-2jti6oV-2iTJNu6-2jtnfug-2jiWsSa-2jv3Yty-2iQ56zx-2iUKGzm-2iQ2obm-2iXUVdF-2k8jrKQ-2jpEB4b-2iQLuDZ-2iQHLb3-2j3t25d-2iUFkLG-2iQHL1P-2iTMzAs-2iGjEcZ-2iTP8Wo-2iQHLhR-2iQNbxR-2iQLuCr-2iTWPHK-2iXWvm4-2iQLuq2-2j3t2c2-2jWUMMr/)
projects:
  - spatial-analysis-of-covid-19
---

*This is a continuation of our series, __COVID-19 and the urban environment__.*

From the first emergence of the COVID-19 pandemic in Wuhan, China to its worldwide spread, the disease has commonly been understood as an urban phenomenon. Urban areas have been hit the hardest, and even those with lesser outbreaks have already seen significant changes to work and social life, and to their urban landscapes and built forms. Over the next several weeks, we will be releasing findings from research we conducted this past summer on COVID and urban life. We aim to provide a broad look at current responses, tactics, and consequences of the pandemic.

**Social inequities**

As much as we would like to believe that we live in an egalitarian society, the COVID-19 pandemic has exposed the deadly consequences of deep-seated inequities that have persisted in North America for centuries. Some have dubbed the virus a “great equalizer,” for everyone is equally as prone to the disease, but is that really the case? Studies have shown that low-income individuals are at a higher risk of chronic illness and less likely to have access to quality healthcare (Government of Canada, 2016). Visible minorities and new immigrants are overrepresented in low-income communities, and newly emerging data shows that they are bearing the brunt of the pandemic in North America (CBC News, 2020). This holds especially true for the Black and Latinx communities that are witnessing the worst outcomes during the pandemic (Calma, 2020). Historic redlining and discriminatory housing and land use policies — all contributing factors of environmental racism — are some of the major systemic causes exacerbating the negative health outcomes for Black and Latinx communities (Green America, 2020). 

Beyond health outcomes directly resulting from COVID-19, communities of color are experiencing heightened discrimination during this time, both from civilians as well as law enforcement officials. Hate crimes against Asian Americans have increased since the beginning of the pandemic (Liu, 2020; Pereira, 2020), to the point that several cities and states have instituted hotlines dedicated to these cases (e.g. City News Service, 2020; NY State Office of the Attorney General, 2020). Ninety percent of the NYPD’s COVID-related arrests targetted Black (66 percent) and Latinx (24 percent) people (McCarthy, 2020). Of the nearly 400 COVID-related summonses issued, more than 80 percent were issued to Black and Latinx people (Marsh et al., 2020). Several other violent interactions with law enforcement and civilians directed toward people of color have occurred during the pandemic, as well (e.g. Mystal, 2020; Natividad, 2020; Sisak, 2020), including the violent killing of Breonna Taylor (Wood, 2020), Ahmaud Arbery by an ex-police officer (Baur & Osborne, 2020), and other Black people. 

Further, women are overrepresented as “essential workers” in North America, daily risking their health on the frontline (Robertson & Gebeloff, 2020). Women are also at a higher risk of job loss, and the rise in reported cases of domestic violence across the world highlights the dangers of such financial precarity (Kennedy, 2020; Neuman, 2020). And the list continues. The homeless population have nowhere to shelter in place, putting them at a higher risk of contracting and spreading the virus (Griswold, 2020). Members of the LGBTQI community are more likely to experience poverty and homelessness, as well as general and healthcare-related discrimination, which makes them exceptionally vulnerable during the ongoing pandemic (Wyton, 2020; Human Rights Campaign Foundation, 2020). Lastly, even those receiving care are potentially at greater risk due to biases in the medical community and designation of scarce resources. This is especially true for blacks and latinxs whose quality of life assessment may be lower due to health disparities brought on by environmental racism, as well as for for the elderly and the disabled who are already more likely to be financially, socially, and medially vulnerable to COVID-19 (Brown, 2020; Pulrang, 2020; Schmidt, 2020; Tartak and Khidir, 2020). 

Countless other examples exist, from discrimination in parks and public places, to unequal access to PPE and testing. One map shows the disparity in COVID testing locations in Philadelphia, with testing sites disproportionately located in higher income and whiter neighbourhoods. Additionally testing sites are predominantly located in neighbourhoods with the lowest percentages of essential workers, revealing disparities in access to testing for some of Philadelphia’s most vulnerable residents (Graetz, 2020). 

The recent outbreak of COVID-19 at the Cargill plant in Alberta, the site of the largest outbreak linked to a single facility in North America, is a good local example of how social inequities are surfacing from the pandemic. Cargill, the multibillion dollar American company, “has been accused by employees and the union of caring more about its bottom line than worker wellbeing” due to their controversial hiring practices (Dryden & Rieger, 2020). Most workers are recent immigrants or temporary foreign workers who speak limited to no English. As many immigrants, they are more worried about their job security to remain in the country than their own health, making them ideal workers for a compromised work environment such as Cargill. The virus has since spread to a nearby First Nations reserve, whose food security and access to quality healthcare and appropriate sanitation infrastructure are already subpar (Dryden & Rieger, 2020; Meloney, 2020). 

However, the Canadian story of COVID and related social inequities, especially in terms of environmental racism, is currently unclear. Empirical studies of how the pandemic is impacting Canadians cannot be made because of a huge gap in data. As of now, Canada is only gathering age and sex as demographic data, even though there is a clear pattern emerging in income and race disparities. “Beyond sex and age, though, we're in the dark. There is no data on Canadian COVID-19 patients' income levels, race, gender identity or physical environments. These are four of the many factors known as social determinants of health – circumstances that do not directly measure physical health but are known to affect it.” (Flanagan, 2020). Toronto started collecting race-based data in late April. The lack of data makes it impossible to quantify the problem and issue specific health mandates that can save lives that are currently disproportionately affected. 


**The challenge of inequities in parks** 

Disparities in treatment of different people in public spaces have long been documented, with people of color and lower income and homeless individuals at higher risk of police attention and interference (Mystal, 2020; Natividad, 2020; Sisak, 2020), as well as having overall less (safe) access to neighbourhood parks (Boone et al., 2009; Mock, 2016; Moore, 2019; Sister et al., 2010; as discussed further below). As COVID-19 spreads and targets already-marginalized communities, access to and safety in public spaces provides a place for people to get fresh air, exercise, and simply to spend time outside of whatever their home circumstances may be. Parks, as spaces for these activities for both individuals, families, and social distanced meetups, are no exception. Pre-existing inequities have only been amplified as lockdown and stay-at-home orders continue. Within the context of the COVID-19 pandemic, cities will need to address certain key gaps in park equity: accessibility, funding and space (Surico, 2020).

In the U.S. alone, 100 million people, inclusive of 28 million children do not have access to a neighbourhood park within 10 minutes walk from home (Surico, 2020). This statement is echoed by Javorsky (2020), who asserts that “residents with lower incomes are less likely to find green space nearby in their neighborhoods in several major U.S. metro areas”. A study done by the City of London in the U.K. revealed that for every pound spent on parks, the return to the taxpayer is 27 pounds when you add up health and air pollution savings with effects on property values, but the author asserts that who has access to that 27 pounds worth of benefits persists, if not worsens, in pandemic times.

The effects of claustrophobia during a pandemic vary with class and income. While being cooped up in a house with a big backyard is stressful, for residents of apartments who don’t have access to a private outdoor space, they rely on parks and getting out of the house for the mental health benefits (Ewing, 2020). This is echoed by Iveson (2020) who asserts that restrictions on public space have greater impacts on people who have less access to private space and that people without stable homes and with restricted access to domestic space, tend to live more of their lives in public spaces. As such, researchers and activists are demanding that restrictions on public spaces be accompanied by provisions to make people’s lives less precarious such as bans on evictions and safe and free accommodations for rough sleepers (Iveson, 2020). The disparity between the rich and the poor in mental and physical health will continue to expand if ensuring everyone in the community has equitable access to outdoor space is not addressed (Ibid).

As stated by Surico (2020), “even if you have a park within 10 minutes of your home, that doesn’t necessarily mean much if the park or playground is not well-maintained or well-designed.” Surico (2020) went on to state that the average New York City park is approximately 73 years old would have probably seen a major renovation around 1997. The author asserted that at least 20% of the city’s parks hadn’t seen a renovation in 25 years with issues such as clogged drainages, broken comfort stations, and vulnerable bridge structures being the most apparent.” This lack of funding is especially evident in working class communities which are hit hardest by the pandemic as most of the parks in need of renovation are smaller neighbourhood green spaces which are the open spaces relied on most by people during the pandemic. (Surico, 2020).

This inequity is persistent in many park systems around the world and stems from the ways in which private wealth and public dollars function. For example, concerns such as community safety or health take budgetary precedence in low-income areas which puts parks towards the bottom of the spending priorities, while parks like Central Park and the High Line in New York have conservancies backed by rich neighbours affording them amenities such as “Beaux Arts bathrooms” and high-quality landscaping (Surico, 2020). 

As aforementioned, social distancing protocols as a measure to contain and prevent the spread of COVID-19 has revealed that cars have taken up so much space that there is not enough room for people (Roberts, 2020). With cars still dominating urban parks (Surico, 2020), social distancing is thus hard to maintain not only in the streets, but in public spaces like parks too. In an article by Ewing (2020), a Toronto resident by the name of Lloyd Alter criticised the lack of space for people who walk, run or bike, stating that “you look at the streets and they're completely empty and you look at the sidewalks and they're completely crowded”. In the same article by Ewing (2020). 

---

<font size = 3>**REFERENCES**

Baur, B. & Osborne, M. (2020, May 14). Gregory McMichael, ex-police officer charged with killing Ahmaud Arbery, had service weapon suspended in 2019. Retrieved from https://abcnews.go.com/US/gregory-mcmichael-police-officer-charged-killing-ahmaud-arbery/story?id=70690972 

Boone, S. A., & Gerba, C. P. (2007). Significance of Fomites in the Spread of Respiratory and Enteric Viral Disease. Applied and Environmental Microbiology, 73(6), 1687–1696. doi: 10.1128/aem.02051-06

Brown, B. (2020, March 25). The Ethical Allocation of Scarce Resources in the US During the COVID-19 Pandemic: The Role of Bioethics. Retrieved from https://blog.petrieflom.law.harvard.edu/2020/03/25/allocation-of-scarce-resources-in-the-covid-19-pandemic-bioethics-ventilators/ 

CBC News. (2020, May 12). Lower income people, new immigrants at higher COVID-19 risk in Toronto, data suggests. CBC. https://www.cbc.ca/news/canada/toronto/low-income
-immigrants-covid-19-infection-1.5566384

Calma, J. (2020, April 8). America set up black communities to be harder hit by COVID-19. The Verge. https://www.theverge.com/2020/4/8/21213974/african-americans-covid-19-coronavirus-race-disparities

City News Service. (2020, April 30). San Diego DA Establishes Tip Line For Asian Americans To Report Coronavirus-Related Hate Crimes. Retrieved from https://www.kpbs.org/news/2020/apr/30/san-diego-da-establishes-tip-line-asian-americans-/ 

Dryden, J. & Rieger, S. (2020, May 6). Inside the slaughterhouse. CBC. https://newsinteractives.cbc.ca/longform/cargill-covid19-outbreak

Ewing, L. (2020, April 18). Growing calls to re-open parks, expand streets to pedestrians amid COVID-19. Retrieved from https://www.ctvnews.ca/health/coronavirus/growing-calls-to-re-open-parks-expand-streets-to-pedestrians-amid-covid-19-1.4901999

Flanagan, R. (2020, April 15). Does COVID-19 discriminate? This is how some Canadians are harder-hit. CTV News. https://www.ctvnews.ca/health/coronavirus/does-covid-19
-discriminate-this-is-how-some-canadians-are-harder-hit-1.4897298

Green America. (2020, April 17). Environmental justice's role in the COVID-19 crisis. Green America. https://www.greenamerica.org/blog/how-environmental-justice-connects-covid-19

Government of Canada. (2016). A backgrounder on poverty in Canada. Government of Canada.https://www.canada.ca/en/employment-social-development/programs/poverty-reduction/backgrounder.html#h2.7-h3.3

Graetz, N. (2020). COVID-19 in Philadelphia. Accessed on May 19, 2020. Retrieved from https://nikilsaval.com/covid-19-in-philadelphia/ 

Griswold, E. (2020, March 26). How do you shelter in place when you don’t have a home? The New Yorker. https://www.newyorker.com/news/dispatch/how-do-you-shelter-in-place-when-you-dont-have-a-home

Human Rights Campaign Foundation. (2020, March 20). The lives & livelihoods of many in the LGBTQ community are at risk amidst COVID-19 crisis. Human Rights Campaign Foundation. https://assets2.hrc.org/files/assets/resources/COVID19-IssueBrief-032020
-FINAL.pdf?_ga=2.34905570.2132853666.1586451351-508168252.1586451351

Iveson, K. (2020, May 7). We don't know what we've got till it's gone – we must reclaim public space lost to the coronavirus crisis. Retrieved from https://theconversation.com/we-dont-know-what-weve-got-till-its-gone-we-must-reclaim-public-space-lost-to-the-coronavirus-crisis-135817

Javorsky, N. (2020, February 5). These cities are addressing inequality in parks access. Retrieved from https://thehill.com/changing-america/sustainability/infrastructure/481596-these-cities-are-addressing-inequality-in

Kennedy, B. (2020, March 25). Two million Canadians could soon be out of work — and women and low-wage workers will be hit the hardest. The Star. https://www.thestar.com/business/2020/03/25/two-million-canadians-could-soon-be-out-of-work-and-women-and-low-wage-workers-will-be-hit-the-hardest.html

Liu, E. (2020, April 11). Covid-19 has inflamed racism against Asian-Americans. Here's how to fight back. Retrieved from  https://www.cnn.com/2020/04/10/opinions/how-to-fight-bias-against-asian-americans-covid-19-liu/index.html 

Marsh, S. (2020, September 26). Escape to the country: how Covid is driving an exodus from Britain’s cities. The Guardian. Retrieved from https://www.theguardian.com/world/2020/sep/26/escape-country-covid-exodus-britain-cities-pandemic-urban-green-space 

McCarthy, C. (2020, May 12). People of color account for 90 percent of NYPD’s ‘COVID-19-related’ arrests. Retrieved from https://nypost.com/2020/05/12/blacks-hispanics-majority-of-nyc-coronavirus-related-arrests/ 

Meloney, N. (2020, May 21). Measures to stop spread of COVID-19 in First Nations limited by lack of infrastructure: report. Retrieved from https://www.cbc.ca/news/indigenous/covid-19-manitoba-first-nations-risk-let-them-eat-cake-1.5578448

Mock, B. (2016, June 2). For African Americans, Park Access Is About More Than Just Proximity. Retrieved from https://www.bloomberg.com/news/articles/2016-06-02/a-legacy-of-racism-in-america-s-parks

Moore, S. (2019, August 9). Park Inequities Are Symptoms of a Bigger Problem. Retrieved from https://healthyplacesbydesign.org/park-inequities-are-symptoms-of-a-bigger-problem/

Mystal, E. (2020, May 5). Covid Is About to Become the Newest Excuse for Police Brutality. Retrieved from https://www.thenation.com/article/society/coronavirus-police-brutality/ 
 
Natividad, I. (2020, April 23). Among the reasons COVID-19 is worse for black communities: Police violence. Retrieved from https://news.berkeley.edu/2020/04/23/one-reason-covid-19-is-worse-for-black-communities-police-violence/ 

Neuman, S. (2020, April 6). Global lockdowns resulting in 'horrifying surge' in domestic violence, U.N. warns. NPR. https://www.npr.org/sections/coronavirus-live-updates/2020/04/06/827908402/global-lockdowns-resulting-in-horrifying-surge-in-domestic-violence-u-n-warns

New York State Office of the Attorney General. (2020, March 23). AG James Launches Hotline to Combat Coronavirus Hate Crimes and Xenophobic Rhetoric. Retrieved from https://ag.ny.gov/press-release/2020/ag-james-launches-hotline-combat-coronavirus-hate-crimes-and-xenophobic-rhetoric 

Pereira, S. (2020, April 19). NYC Human Rights Commission Forms COVID-19 Team After Anti-Asian Discrimination Skyrockets. Retrieved from https://gothamist.com/news/nyc-human-rights-commission-forms-covid-19-team-after-anti-asian-discrimination-skyrockets 

Pulrang, A. (2020, April 30). COVID-19 teaches us a lot about differences in the disability community. Forbes. https://www.forbes.com/sites/andrewpulrang/2020/04/30/covid-19
-teaches-us-a-lot-about-differences-in-the-disability-community/#1e2448827714

Roberts, D. (2020, April 13). How to make a city livable during lockdown. Retrieved from https://www.vox.com/cities-and-urbanism/2020/4/13/21218759/coronavirus-cities-lockdown-covid-19-brent-toderian

Robertson, C. & Gebeloff, R. (2020, April 18). How millions of women became the most essential workers in America. The New York Times. https://www.nytimes.com/2020/04/18/us/coronavirus-women-essential-workers.html?action=click&module=Spotlight&pgtype=Homepage

Schmidt, H. (2020, April 15). The way we ration ventilators is biased. The New York Times. https://www.nytimes.com./2020/04/15/opinion/covid-ventilator-rationing-blacks.html

Sisak, M. (2020, May 4). NYPD criticized over viral videos depicting violent arrests for alleged social distancing infractions. TIME. https://time.com/5831717/nypd-arrests-coronavirus-social-distancing/

Sister, C., Wolch, J., & Wilson, J. (2010). Got green? Addressing environmental justice in park
provision. GeoJournal, 75(3), 229-248. doi: 10.1007/s10708-009-9303-8

Surico, J. (2020, April 13). The Power of Parks in a Pandemic. Retrieved from https://www.citylab.com/perspective/2020/04/coronavirus-nature-city-park-funding-accessibility-location/609697/

Tartak, J. C. & Khidir, H. (2020, April 21). Opinion: U.S. Must Avoid Building Racial Bias Into COVID-19 Emergency Guidance. Retrieved from https://www.npr.org/sections/health-shots/2020/04/21/838763690/opinion-u-s-must-avoid-building-racial-bias-into-covid-19-emergency-guidance 

Wood, J. (2020, May 14). Breonna Taylor shooting: hunt for answers in case of black woman killed by police. Retrieved from https://www.theguardian.com/us-news/2020/may/14/breonna-taylor-louisville-police-shooting-kentucky 

Wyton, M. (2020, May 6). Queer Canadians ‘particularly vulnerable’ to effects of COVID-19. The Tyee. https://thetyee.ca/News/2020/05/06/Queer-Canadians-Vulnerable-COVID19/